apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: details
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/jenisakthi/k8-app-sample.git
    path: kubernetes/details
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
      - Replace=true
    retry:
      limit: 5
      backoff:
        duration: 60s
        factor: 2
        maxDuration: 6m0s